CREATE TABLE [dbo].[TRA_EVENT_TEAM] (
    [EVENT_TEAMS_ID]       INT IDENTITY (1, 1) NOT NULL,
    [EVENT_ID] INT NOT NULL,
    [TEAM_ID]  INT NOT NULL,
	[EFFECTIVE_START_DATE] DATETIME NULL, 
	[EFFECTIVE_END_DATE] DATETIME NULL, 
	[CREATED_BY_USER] VARCHAR(255) NULL, 
	[CREATED_BY_DATE] DATETIME NULL, 
	[LAST_UPDATED_BY_USER] VARCHAR(255) NULL, 
	[LAST_UPDATED_BY_DATE] DATETIME NULL,
    CONSTRAINT [PK_EVENT_TEAMS] PRIMARY KEY CLUSTERED ([EVENT_TEAMS_ID] ASC),
    CONSTRAINT [FK_EVENT_EVENT_TEAMS] FOREIGN KEY ([EVENT_ID]) REFERENCES [dbo].[TRA_EVENT] ([EVENT_ID]),
    CONSTRAINT [FK_EVENT_TEAMS_TEAM] FOREIGN KEY ([TEAM_ID]) REFERENCES [dbo].[TRA_TEAM] ([TEAM_ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_FK_EVENT_EVENT_TEAMS]
    ON [dbo].[TRA_EVENT_TEAM]([EVENT_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_FK_EVENT_TEAMS_TEAM]
    ON [dbo].[TRA_EVENT_TEAM]([TEAM_ID] ASC);

