CREATE TABLE [dbo].[TRA_USER] (
    [USER_ID]               INT            IDENTITY (1, 1) NOT NULL,
    [USERNAME]             VARCHAR(255) NOT NULL,
    [DIRECTORY ] VARCHAR(8) NOT NULL,
	[GUID] VARCHAR(255) NOT NULL,
    [REGION]           VARCHAR(255) NOT NULL,
    [FNAME]            VARCHAR(255) NOT NULL,
    [LNAME]            VARCHAR(255) NOT NULL,
    [DESCRIPTION]      VARCHAR(1024) NOT NULL,
    [EMAIL]            VARCHAR(1024) NOT NULL,
    [ROLE_ID]      INT            NOT NULL,
    [TEAM_ID]       INT,
	[EFFECTIVE_START_DATE] DATETIME NULL, 
	[EFFECTIVE_END_DATE] DATETIME NULL, 
	[CREATED_BY_USER] VARCHAR(255) NULL, 
	[CREATED_BY_DATE] DATETIME NULL, 
	[LAST_UPDATED_BY_USER] VARCHAR(255) NULL, 
	[LAST_UPDATED_BY_DATE] DATETIME NULL,
     
     
    CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED ([USER_ID] ASC),
    CONSTRAINT [FK_USER_ROLE] FOREIGN KEY ([ROLE_ID]) REFERENCES [dbo].[TRA_ROLE] ([ROLE_ID]),
    CONSTRAINT [FK_USER_TEAM] FOREIGN KEY ([TEAM_ID]) REFERENCES [dbo].[TRA_TEAM] ([TEAM_ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_FK_USER_ROLES]
    ON [dbo].[TRA_USER]([ROLE_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_FK_UserTEAM]
    ON [dbo].[TRA_USER]([TEAM_ID] ASC);



