CREATE TABLE [dbo].[TRA_TOPIC] (
    [TOPIC_ID]      INT            IDENTITY (1, 1) NOT NULL,
    [TITLE]   VARCHAR(1024) NOT NULL,
    [USER_ID] INT            NOT NULL,
	[EFFECTIVE_START_DATE] DATETIME NULL, 
	[EFFECTIVE_END_DATE] DATETIME NULL, 
	[CREATED_BY_USER] VARCHAR(255) NULL, 
	[CREATED_BY_DATE] DATETIME NULL, 
	[LAST_UPDATED_BY_USER] VARCHAR(255) NULL, 
	[LAST_UPDATED_BY_DATE] DATETIME NULL,
    CONSTRAINT [PK_THREAD] PRIMARY KEY CLUSTERED ([TOPIC_ID] ASC),
    CONSTRAINT [FK_USER_THREAD] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[TRA_USER] ([USER_ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_FK_USER_THREAD]
    ON [dbo].[TRA_TOPIC_MESSAGE]([USER_ID] ASC);

