CREATE TABLE [dbo].[TRA_EVENT] (
    [EVENT_ID]          INT            IDENTITY (1, 1) NOT NULL,
    [START_DATE]  DATETIME NOT NULL,
    [END_DATE]    DATETIME NOT NULL,
    [DESCRIPTION] TEXT NOT NULL,
	[EFFECTIVE_START_DATE] DATETIME NULL, 
	[EFFECTIVE_END_DATE] DATETIME NULL, 
	[CREATED_BY_USER] VARCHAR(255) NULL, 
	[CREATED_BY_DATE] DATETIME NULL, 
	[LAST_UPDATED_BY_USER] VARCHAR(255) NULL, 
	[LAST_UPDATED_BY_DATE] DATETIME NULL,
    CONSTRAINT [PK_EVENT] PRIMARY KEY CLUSTERED ([EVENT_ID] ASC)
);

