CREATE TABLE [dbo].[TRA_MEMBER_REQ] (
    [MEMBER_REQ_ID]      INT IDENTITY (1, 1) NOT NULL,
    [USER_ID] INT NOT NULL,
    [TEAM_ID] INT NOT NULL,
	[EFFECTIVE_START_DATE] DATETIME NULL, 
	[EFFECTIVE_END_DATE] DATETIME NULL, 
	[CREATED_BY_USER] VARCHAR(255) NULL, 
	[CREATED_BY_DATE] DATETIME NULL, 
	[LAST_UPDATED_BY_USER] VARCHAR(255) NULL, 
	[LAST_UPDATED_BY_DATE] DATETIME NULL,
    CONSTRAINT [PK_MEMBER_REQ] PRIMARY KEY CLUSTERED ([MEMBER_REQ_ID] ASC),
    CONSTRAINT [FK_MEMBER_REQTEAM] FOREIGN KEY ([TEAM_ID]) REFERENCES [dbo].[TRA_TEAM] ([TEAM_ID]),
    CONSTRAINT [FK_USER_MEMBER_REQ] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[TRA_USER] ([USER_ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_FK_USER_MEMBER_REQ]
    ON [dbo].[TRA_MEMBER_REQ]([USER_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_FK_MEMBER_REQTEAM]
    ON [dbo].[TRA_MEMBER_REQ]([TEAM_ID] ASC);

