CREATE TABLE [dbo].[TRA_ACTIVITY] (
    [ACTIVITY_ID]        INT            IDENTITY (1, 1) NOT NULL,
    [NAME]      VARCHAR(1024) NOT NULL,
	[DESCRIPTION] VARCHAR(255) NULL,
    [INTENSITY] INT NOT NULL,
    [EFFECTIVE_START_DATE] DATETIME NULL, 
	[EFFECTIVE_END_DATE] DATETIME NULL, 
	[CREATED_BY_USER] VARCHAR(255) NULL, 
	[CREATED_BY_DATE] DATETIME NULL, 
	[LAST_UPDATED_BY_USER] VARCHAR(255) NULL, 
	[LAST_UPDATED_BY_DATE] DATETIME NULL,
     
    CONSTRAINT [PK_ACTIVITY] PRIMARY KEY CLUSTERED ([ACTIVITY_ID] ASC)
);

