CREATE TABLE [dbo].[TRA_TOPIC_MESSAGE] (
    [TOPIC_MESSAGE_ID]        INT            IDENTITY (1, 1) NOT NULL,
    [USER_ID]   INT            NOT NULL,
    [BODY]     TEXT NOT NULL,
    [TOPIC_ID] INT            NOT NULL,
	[EFFECTIVE_START_DATE] DATETIME NULL, 
	[EFFECTIVE_END_DATE] DATETIME NULL, 
	[CREATED_BY_USER] VARCHAR(255) NULL, 
	[CREATED_BY_DATE] DATETIME NULL, 
	[LAST_UPDATED_BY_USER] VARCHAR(255) NULL, 
	[LAST_UPDATED_BY_DATE] DATETIME NULL,
    CONSTRAINT [PK_TOPIC_MESSAGE] PRIMARY KEY CLUSTERED ([TOPIC_MESSAGE_ID] ASC),
    CONSTRAINT [FK_TOPIC_MESSAGE_TOPIC] FOREIGN KEY ([TOPIC_ID]) REFERENCES [dbo].[TRA_TOPIC] ([TOPIC_ID]),
    CONSTRAINT [FK_TOPIC_MESSAGE_USER] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[TRA_USER] ([USER_ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_FK_TOPIC_MESSAGE_USER]
    ON [dbo].[TRA_TOPIC_MESSAGE]([USER_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_FK_TOPIC_MESSAGE_TOPIC]
    ON [dbo].[TRA_TOPIC_MESSAGE]([TOPIC_ID] ASC);

