DELETE FROM TRA_USER_ACTIVITY;
DELETE FROM TRA_TOPIC_MESSAGE;
DELETE FROM TRA_TOPIC;
UPDATE TRA_USER SET CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1, TEAM_ID = null, IS_FREE_AGENT = 0;
UPDATE TRA_IMAGE SET CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1, TEAM_ID = null;
DELETE FROM TRA_IMAGE WHERE TEAM_ID is null AND USER_ID is null;
DELETE FROM TRA_MEMBER_REQ;
DELETE FROM TRA_TEAM;
