export const CREATE_EVENT = 'CREATE_EVENT';
export const FETCH_EVENTS = 'FETCH_EVENTS';
export const FETCH_EVENT = 'FETCH_EVENT';
export const EDIT_EVENT = 'EDIT_EVENT';
export const ARCHIVE_EVENT = 'ARCHIVE_EVENT';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_ADMIN_USERS = 'FETCH_ADMIN_USERS';
export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const EDIT_USER_DESCRIPTION = 'EDIT_USER_DESCRIPTION';

export const FETCH_REGIONS = 'FETCH_REGIONS';
export const FETCH_TEAM = 'FETCH_TEAM';
export const FETCH_TEAMS = 'FETCH_TEAMS';
export const FETCH_CURRENT_TEAM = 'FETCH_CURRENT_TEAM';
export const CREATE_TEAM = 'CREATE_TEAM';

export const UPDATE_AUTH_USER = 'UPDATE_AUTH_USER';

export const FETCH_USER_ACTIVITY = 'FETCH_USER_ACTIVITY';
export const FETCH_USER_ACTIVITIES = 'FETCH_USER_ACTIVITIES';
export const CREATE_USER_ACTIVITY = 'CREATE_USER_ACTIVITY';

export const FETCH_ACTIVITY_LIST = 'FETCH_ACTIVITY_LIST';

export const FETCH_USER_SCORES = 'FETCH_USER_SCORES';
export const FETCH_USER_EVENT_SCORE = 'FETCH_USER_EVENT_SCORE';
export const FETCH_TEAM_SCORES = 'FETCH_TEAM_SCORES';
export const FETCH_TEAM_EVENT_SCORE = 'FETCH_TEAM_EVENT_SCORE';
export const FETCH_TEAM_STANDINGS = 'FETCH_TEAM_STANDINGS';
export const FETCH_REGION_STANDINGS = 'FETCH_REGION_STANDINGS';

export const FETCH_ROLES = 'FETCH_ROLES';
export const FETCH_CURRENT_ROLE = 'FETCH_CURRENT_ROLE';
export const SET_CURRENT_USER_ROLE = 'SET_CURRENT_USER_ROLE';

export const FETCH_ALL_REQUESTS = ' FETCH_ALL_REQUESTS';
export const FETCH_SPECIFIC_TEAM_REQUESTS = 'FETCH_SPECIFIC_TEAM_REQUESTS';
export const POST_REQUEST = 'POST_REQUEST';
export const FETCH_JOIN_REQUESTS = 'FETCH_JOIN_REQUESTS';
export const EDIT_JOIN_REQUEST = 'EDIT_JOIN_REQUEST';
export const DELETE_JOIN_REQUEST = 'DELETE_JOIN_REQUEST';

export const FETCH_TOPICS = 'FETCH_TOPICS';
export const FETCH_TOPIC = 'FETCH_TOPIC';
export const CREATE_TOPIC = 'CREATE_TOPIC';
export const EDIT_TOPIC = 'EDIT_TOPIC';
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POST = 'FETCH_POST';
export const CREATE_POST = 'CREATE_POST';
export const EDIT_POST = 'EDIT_POST';

export const SHOW_ERROR_DIALOG_MODAL = 'SHOW_ERROR_DIALOG_MODAL';
export const HIDE_ERROR_DIALOG_MODAL = 'HIDE_ERROR_DIALOG_MODAL';
