export const CREATE_EVENT = 'CREATE_EVENT';
export const FETCH_EVENTS = 'FETCH_EVENTS';
export const FETCH_EVENT = 'FETCH_EVENT';
export const EDIT_EVENT = 'EDIT_EVENT';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USERS = 'FETCH_USERS';
export const EDIT_USER_DESCRIPTION = 'EDIT_USER_DESCRIPTION';

export const FETCH_REGIONS = 'FETCH_REGIONS';
export const FETCH_TEAM = 'FETCH_TEAM';
export const FETCH_TEAMS = 'FETCH_TEAMS';
export const CREATE_TEAM = 'CREATE_TEAM';

export const FETCH_AUTH_USER = 'FETCH_AUTH_USER';
export const UPDATE_AUTH_USER = 'UPDATE_AUTH_USER';

export const CREATE_USER_ACTIVITY = 'CREATE_USER_ACTIVITY';
export const FETCH_ACTIVITY_LIST = 'FETCH_ACTIVITY_LIST';

export const FETCH_USER_SCORE = 'FETCH_USER_SCORE';
export const FETCH_TEAM_SCORE = 'FETCH_TEAM_SCORE';

export const FETCH_ALL_USER_SCORES = 'FETCH_ALL_USER_SCORES';
export const FETCH_ALL_TEAM_SCORES = 'FETCH_ALL_TEAM_SCORES';

export const FETCH_ROLES = 'FETCH_ROLES';

export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_CURRENT_TEAM = 'FETCH_CURRENT_TEAM';
export const FETCH_CURRENT_ROLE = 'FETCH_CURRENT_ROLE';

export const FETCH_ALL_REQUESTS = ' FETCH_ALL_REQUESTS';
export const FETCH_SPECIFIC_TEAM_REQUESTS = 'FETCH_SPECIFIC_TEAM_REQUESTS';
export const POST_REQUEST = 'POST_REQUEST';
export const FETCH_JOIN_REQUESTS = 'FETCH_JOIN_REQUESTS';
export const EDIT_JOIN_REQUEST = 'EDIT_JOIN_REQUEST';
