/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/


-- Seed TRA_ROLE Table

IF NOT EXISTS (SELECT 1 FROM TRA_ROLE)
BEGIN
    INSERT INTO TRA_ROLE ([NAME], [DESCRIPTION], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER]) 
		VALUES ('Admin', 'Admin role', GETDATE(), 'Transaction_Dev', GETDATE(), 'Transaction_Dev', 1)
	INSERT INTO TRA_ROLE ([NAME], [DESCRIPTION], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER])
		VALUES ('User', 'User role', GETDATE(), 'Transaction_Dev', GETDATE(), 'Transaction_Dev', 1)
END

-- Seed TRA_REGION Table

IF NOT EXISTS (SELECT 1 FROM TRA_REGION)
BEGIN
    INSERT INTO TRA_REGION ([NAME], [DESCRIPTION], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER])
		VALUES ('HQ', 'HQ', GETDATE(), 'Transaction_Dev', GETDATE(), 'Transaction_Dev', 1)
	INSERT INTO TRA_REGION ([NAME], [DESCRIPTION], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER])
		VALUES ('REGION 1', 'REGION 1', GETDATE(), 'Transaction_Dev', GETDATE(), 'Transaction_Dev', 1)
	INSERT INTO TRA_REGION ([NAME], [DESCRIPTION], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER]) 
		VALUES ('REGION 2', 'REGION 2', GETDATE(), 'Transaction_Dev', GETDATE(), 'Transaction_Dev', 1)
	INSERT INTO TRA_REGION ([NAME], [DESCRIPTION], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER]) 
		VALUES ('REGION 3', 'REGION 3', GETDATE(), 'Transaction_Dev', GETDATE(), 'Transaction_Dev', 1)
END

-- Seed TRA_ACTIVITY Table

IF NOT EXISTS (SELECT 1 FROM TRA_ACTIVITY)
BEGIN

	INSERT INTO TRA_ACTIVITY ([NAME], [DESCRIPTION], [INTENSITY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER])
		VALUES ('Walking', 'Walking Low Intensity', 1, GETDATE(), 'Transaction_Dev', GETDATE(), 'Transaction_Dev', 1)
	INSERT INTO TRA_ACTIVITY ([NAME], [DESCRIPTION], [INTENSITY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER])
		VALUES ('Gardening', 'Gardening Low Intensity', 1, GETDATE(), 'Transaction_Dev', GETDATE(), 'Transaction_Dev', 1)
	INSERT INTO TRA_ACTIVITY ([NAME], [DESCRIPTION], [INTENSITY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER])
		VALUES ('Yoga', 'Yoga Low Intensity', 1, GETDATE(), 'Transaction_Dev', GETDATE(), 'Transaction_Dev', 1)
	INSERT INTO TRA_ACTIVITY ([NAME], [DESCRIPTION], [INTENSITY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER])
		VALUES ('Kayaking', 'Kayaking Low Intensity', 1, GETDATE(), 'Transaction_Dev', GETDATE(), 'Transaction_Dev', 1)
	INSERT INTO TRA_ACTIVITY ([NAME], [DESCRIPTION], [INTENSITY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER])
		VALUES ('Pilates', 'Pilates Low Intensity', 1, GETDATE(), 'Transaction_Dev', GETDATE(), 'Transaction_Dev', 1)
	INSERT INTO TRA_ACTIVITY ([NAME], [DESCRIPTION], [INTENSITY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER])
		VALUES ('Swimming', 'Swimming Low Intensity', 1, GETDATE(), 'Transaction_Dev', GETDATE(), 'Transaction_Dev', 1)
	INSERT INTO TRA_ACTIVITY ([NAME], [DESCRIPTION], [INTENSITY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER])
		VALUES ('Other', 'Other Low Intensity', 1, GETDATE(), 'Transaction_Dev', GETDATE(), 'Transaction_Dev', 1)

	INSERT INTO TRA_ACTIVITY ([NAME], [DESCRIPTION], [INTENSITY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER])
		VALUES ('Brisk Walking', 'Brisk Walking Medium Intensity', 2, GETDATE(), 'Transaction_Dev', GETDATE(), 'Transaction_Dev', 1)
	INSERT INTO TRA_ACTIVITY ([NAME], [DESCRIPTION], [INTENSITY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER])
		VALUES ('Water Aerobics', 'Water Aerobics Medium Intensity', 2, GETDATE(), 'Transaction_Dev', GETDATE(), 'Transaction_Dev', 1)
	INSERT INTO TRA_ACTIVITY ([NAME], [DESCRIPTION], [INTENSITY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER])
		VALUES ('Jogging', 'Jogging Medium Intensity', 2, GETDATE(), 'Transaction_Dev', GETDATE(), 'Transaction_Dev', 1)
	INSERT INTO TRA_ACTIVITY ([NAME], [DESCRIPTION], [INTENSITY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER])
		VALUES ('Hiking', 'Hiking Medium Intensity', 2, GETDATE(), 'Transaction_Dev', GETDATE(), 'Transaction_Dev', 1)
	INSERT INTO TRA_ACTIVITY ([NAME], [DESCRIPTION], [INTENSITY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER])
		VALUES ('Cycling', 'Cycling Medium Intensity', 2, GETDATE(), 'Transaction_Dev', GETDATE(), 'Transaction_Dev', 1)
	INSERT INTO TRA_ACTIVITY ([NAME], [DESCRIPTION], [INTENSITY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER])
		VALUES ('Dancing', 'Dancing Medium Intensity', 2, GETDATE(), 'Transaction_Dev', GETDATE(), 'Transaction_Dev', 1)
	INSERT INTO TRA_ACTIVITY ([NAME], [DESCRIPTION], [INTENSITY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER])
		VALUES ('Other', 'Other Medium Intensity', 2, GETDATE(), 'Transaction_Dev', GETDATE(), 'Transaction_Dev', 1)

	INSERT INTO TRA_ACTIVITY ([NAME], [DESCRIPTION], [INTENSITY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER])
		VALUES ('Running', 'Running High Intensity', 3, GETDATE(), 'Transaction_Dev', GETDATE(), 'Transaction_Dev', 1)
	INSERT INTO TRA_ACTIVITY ([NAME], [DESCRIPTION], [INTENSITY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER])
		VALUES ('Rowing', 'Rowing High Intensity', 3, GETDATE(), 'Transaction_Dev', GETDATE(), 'Transaction_Dev', 1)
	INSERT INTO TRA_ACTIVITY ([NAME], [DESCRIPTION], [INTENSITY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER])
		VALUES ('Hot Yoga', 'Hot Yoga High Intensity', 3, GETDATE(), 'Transaction_Dev', GETDATE(), 'Transaction_Dev', 1)
	INSERT INTO TRA_ACTIVITY ([NAME], [DESCRIPTION], [INTENSITY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER])
		VALUES ('Soccer', 'Soccer High Intensity', 3, GETDATE(), 'Transaction_Dev', GETDATE(), 'Transaction_Dev', 1)
	INSERT INTO TRA_ACTIVITY ([NAME], [DESCRIPTION], [INTENSITY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER])
		VALUES ('Aerobics', 'Aerobics High Intensity', 3, GETDATE(), 'Transaction_Dev', GETDATE(), 'Transaction_Dev', 1)
	INSERT INTO TRA_ACTIVITY ([NAME], [DESCRIPTION], [INTENSITY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER])
		VALUES ('Squash', 'Squash High Intensity', 3, GETDATE(), 'Transaction_Dev', GETDATE(), 'Transaction_Dev', 1)
	INSERT INTO TRA_ACTIVITY ([NAME], [DESCRIPTION], [INTENSITY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER])
		VALUES ('Strength Training', 'Strength Training High Intensity', 3, GETDATE(), 'Transaction_Dev', GETDATE(), 'Transaction_Dev', 1)
	INSERT INTO TRA_ACTIVITY ([NAME], [DESCRIPTION], [INTENSITY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER])
		VALUES ('Basketball', 'Basketball High Intensity', 3, GETDATE(), 'Transaction_Dev', GETDATE(), 'Transaction_Dev', 1)
	INSERT INTO TRA_ACTIVITY ([NAME], [DESCRIPTION], [INTENSITY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER])
		VALUES ('CrossFit', 'CrossFit High Intensity', 3, GETDATE(), 'Transaction_Dev', GETDATE(), 'Transaction_Dev', 1)
	INSERT INTO TRA_ACTIVITY ([NAME], [DESCRIPTION], [INTENSITY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER])
		VALUES ('Volleyball', 'Volleyball High Intensity', 3, GETDATE(), 'Transaction_Dev', GETDATE(), 'Transaction_Dev', 1)
	INSERT INTO TRA_ACTIVITY ([NAME], [DESCRIPTION], [INTENSITY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER])
		VALUES ('Other', 'Other High Intensity', 3, GETDATE(), 'Transaction_Dev', GETDATE(), 'Transaction_Dev', 1)
END

-- Seed TRA_CONTENT_TYPE Table

IF NOT EXISTS (SELECT 1 FROM TRA_CONTENT_TYPE)
BEGIN
	INSERT INTO TRA_CONTENT_TYPE ([NAME],  [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER])
		VALUES ('Main', GETDATE(), 'Transaction_Dev', GETDATE(), 'Transaction_Dev', 1)
	INSERT INTO TRA_CONTENT_TYPE ([NAME],  [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER])
		VALUES ('FAQ', GETDATE(), 'Transaction_Dev', GETDATE(), 'Transaction_Dev', 1)
	INSERT INTO TRA_CONTENT_TYPE ([NAME],  [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER]) 
		VALUES ('Incentives', GETDATE(), 'Transaction_Dev', GETDATE(), 'Transaction_Dev', 1)
END


-- 2.3 Migration, set last message create timestamp on topics
IF EXISTS (SELECT 1 FROM TRA_TOPIC WHERE LAST_MESSAGE_TIMESTAMP IS NULL)
BEGIN
UPDATE T

SET T.[LAST_MESSAGE_TIMESTAMP] =  
(CASE 
	WHEN T.[DB_CREATE_TIMESTAMP] > (SELECT MAX(M.[DB_CREATE_TIMESTAMP]) FROM [TRA_TOPIC_MESSAGE] M WHERE M.TOPIC_ID = T.TOPIC_ID) 
	THEN T.[DB_CREATE_TIMESTAMP] 
	ELSE (SELECT MAX(M.[DB_CREATE_TIMESTAMP]) FROM [TRA_TOPIC_MESSAGE] M WHERE M.TOPIC_ID = T.TOPIC_ID) 
 END)
, T.[CONCURRENCY_CONTROL_NUMBER] = T.[CONCURRENCY_CONTROL_NUMBER] + 1

FROM [TRA_TOPIC] T
END