apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: transaction
labels:
  template: reverse-proxy
objects:
  - apiVersion: v1
    data:
      conf${SUFFIX}: |-
        server {
            listen       8080 default_server;
            listen       [::]:8080 default_server;
            server_name  _;

            location / {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_pass http://transaction-client${SUFFIX}:8080;
            }
            
            location /api {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_pass http://transaction-api${SUFFIX}:8080/api;
            }
        }
    kind: ConfigMap
    metadata:
      name: reverse-proxy-${SUFFIX}
  - apiVersion: v1
    kind: ImageStream
    metadata:
      creationTimestamp: null
      labels:
        shared: true
      name: transaction-nginx
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      creationTimestamp: null
      name: ${NAME}${SUFFIX}
    spec:
      replicas: 1
      selector:
        deploymentconfig: ${NAME}${SUFFIX}
      strategy:
        resources:
          requests:
            cpu: 250m
            memory: 32Mi
          limits:
            cpu: 250m
            memory: 64Mi
      template:
        metadata:
          creationTimestamp: null
          labels:
            deploymentconfig: ${NAME}${SUFFIX}
        spec:
          containers:
            - image: transaction-nginx:${VERSION}
              name: reverse-proxy
              resources:
                requests:
                  cpu: 250m
                  memory: 32Mi
                limits:
                  cpu: 250m
                  memory: 64Mi
              ports:
                - containerPort: 8080
                  protocol: TCP
              volumeMounts:
                - name: ${NAME}${SUFFIX}-volume
                  mountPath: /etc/nginx/conf.d/
                  readOnly: true
          volumes:
            - name: ${NAME}${SUFFIX}-volume
              configMap:
                defaultMode: 420
                items:
                  - key: conf${SUFFIX}
                    path: default.conf
                name: reverse-proxy-${SUFFIX}
      test: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - reverse-proxy
            from:
              kind: ImageStreamTag
              name: transaction-nginx:${VERSION}
          type: ImageChange
  - apiVersion: v1
    kind: Service
    metadata:
      creationTimestamp: null
      name: ${NAME}${SUFFIX}
    spec:
      ports:
        - name: web
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: ${NAME}${SUFFIX}
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      creationTimestamp: null
      name: ${NAME}${SUFFIX}
    spec:
      host:
      port:
        targetPort: web
      tls:
        termination: edge
      to:
        kind: Service
        name: ${NAME}${SUFFIX}
        weight: 100
      wildcardPolicy: None
parameters:
  - displayName: NAME
    name: NAME
    required: true
    value: ""
  - displayName: SUFFIX
    name: SUFFIX
    required: true
    value: ""
  - displayName: VERSION
    name: VERSION
    required: true
    value: ""
  - description: SOURCE_REPOSITORY_URL
    displayName: SOURCE_REPOSITORY_URL
    name: SOURCE_REPOSITORY_URL
    required: false
    value: ""
  - description: SOURCE_REPOSITORY_REF
    displayName: SOURCE_REPOSITORY_REF
    name: SOURCE_REPOSITORY_REF
    required: false
    value: ""
